// <auto-generated />
using System;
using ConferenceApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ConferenceApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191120224430_CreateFileModelAndFileViewModel")]
    partial class CreateFileModelAndFileViewModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ConferenceApp.Models.CheckBoxItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EventId");

                    b.Property<bool>("IsChecked");

                    b.Property<int>("TagId");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("CheckBoxItems");
                });

            modelBuilder.Entity("ConferenceApp.Models.Conference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Conferences");
                });

            modelBuilder.Entity("ConferenceApp.Models.ConferenceVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConferenceId");

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("EventCentreId");

                    b.Property<int>("Number");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("EventCentreId");

                    b.ToTable("ConferenceVersions");
                });

            modelBuilder.Entity("ConferenceApp.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConferenceVersionId");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("RoomId");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceVersionId");

                    b.ToTable("Events");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Event");
                });

            modelBuilder.Entity("ConferenceApp.Models.EventCentre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Latitude");

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<float>("Longitude");

                    b.Property<string>("MapImage");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("EventCentre");
                });

            modelBuilder.Entity("ConferenceApp.Models.EventTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ChatId");

                    b.Property<int>("EventId");

                    b.Property<int?>("PracticalSessionId");

                    b.Property<int>("TagId");

                    b.Property<int?>("TalkId");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("EventId");

                    b.HasIndex("PracticalSessionId");

                    b.HasIndex("TagId");

                    b.HasIndex("TalkId");

                    b.ToTable("EventTags");
                });

            modelBuilder.Entity("ConferenceApp.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Message")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("ConferenceApp.Models.FeedbackCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("FeedbackCategories");
                });

            modelBuilder.Entity("ConferenceApp.Models.FeedbackScope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FeedbackCategoryId");

                    b.Property<int?>("FeedbackId");

                    b.Property<int>("Grade");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackCategoryId");

                    b.HasIndex("FeedbackId");

                    b.ToTable("FeedbackScopes");
                });

            modelBuilder.Entity("ConferenceApp.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("EventId");

                    b.Property<string>("Path")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("ConferenceApp.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Message")
                        .IsRequired();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ConferenceApp.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EventId");

                    b.Property<string>("Name");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ConferenceApp.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EquipmentDescription");

                    b.Property<int>("EventCentreId");

                    b.Property<int>("MaxCapacity");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("EventCentreId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("ConferenceApp.Models.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ConferenceId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceId");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("ConferenceApp.Models.Sponsorship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConferenceVersionId");

                    b.Property<string>("Name");

                    b.Property<int>("SponsorId");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceVersionId");

                    b.HasIndex("SponsorId");

                    b.ToTable("Sponsorships");
                });

            modelBuilder.Entity("ConferenceApp.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ConferenceApp.Models.ViewModels.FileViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EventId");

                    b.Property<string>("FileDescription");

                    b.HasKey("Id");

                    b.ToTable("FileViewModels");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ConferenceApp.Models.Chat", b =>
                {
                    b.HasBaseType("ConferenceApp.Models.Event");

                    b.Property<string>("Moderator");

                    b.Property<string>("Panelists");

                    b.Property<string>("Topic")
                        .IsRequired();

                    b.HasDiscriminator().HasValue("Chat");
                });

            modelBuilder.Entity("ConferenceApp.Models.FoodService", b =>
                {
                    b.HasBaseType("ConferenceApp.Models.Event");

                    b.Property<string>("Category")
                        .IsRequired();

                    b.HasDiscriminator().HasValue("FoodService");
                });

            modelBuilder.Entity("ConferenceApp.Models.Party", b =>
                {
                    b.HasBaseType("ConferenceApp.Models.Event");

                    b.Property<string>("MusicStyle")
                        .IsRequired();

                    b.HasDiscriminator().HasValue("Party");
                });

            modelBuilder.Entity("ConferenceApp.Models.PracticalSession", b =>
                {
                    b.HasBaseType("ConferenceApp.Models.Event");

                    b.Property<string>("ComplementaryMaterial")
                        .IsRequired();

                    b.Property<string>("Exhibitor");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnName("PracticalSession_Topic");

                    b.HasDiscriminator().HasValue("PracticalSession");
                });

            modelBuilder.Entity("ConferenceApp.Models.Talk", b =>
                {
                    b.HasBaseType("ConferenceApp.Models.Event");

                    b.Property<string>("ComplementaryMaterial")
                        .IsRequired()
                        .HasColumnName("Talk_ComplementaryMaterial");

                    b.Property<string>("Exhibitor")
                        .HasColumnName("Talk_Exhibitor");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnName("Talk_Topic");

                    b.HasDiscriminator().HasValue("Talk");
                });

            modelBuilder.Entity("ConferenceApp.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Age")
                        .IsRequired();

                    b.Property<string>("Biography");

                    b.Property<string>("ContactInfo");

                    b.Property<string>("Cv");

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("ConferenceApp.Models.CheckBoxItem", b =>
                {
                    b.HasOne("ConferenceApp.Models.Event")
                        .WithMany("AvailableTags")
                        .HasForeignKey("EventId");
                });

            modelBuilder.Entity("ConferenceApp.Models.ConferenceVersion", b =>
                {
                    b.HasOne("ConferenceApp.Models.Conference")
                        .WithMany("Versions")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConferenceApp.Models.EventCentre")
                        .WithMany("ConferenceVersions")
                        .HasForeignKey("EventCentreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConferenceApp.Models.Event", b =>
                {
                    b.HasOne("ConferenceApp.Models.ConferenceVersion")
                        .WithMany("Events")
                        .HasForeignKey("ConferenceVersionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConferenceApp.Models.EventTag", b =>
                {
                    b.HasOne("ConferenceApp.Models.Chat")
                        .WithMany("EventTags")
                        .HasForeignKey("ChatId");

                    b.HasOne("ConferenceApp.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConferenceApp.Models.PracticalSession")
                        .WithMany("EventTags")
                        .HasForeignKey("PracticalSessionId");

                    b.HasOne("ConferenceApp.Models.Tag", "Tag")
                        .WithMany("EventTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConferenceApp.Models.Talk")
                        .WithMany("EventTags")
                        .HasForeignKey("TalkId");
                });

            modelBuilder.Entity("ConferenceApp.Models.FeedbackScope", b =>
                {
                    b.HasOne("ConferenceApp.Models.FeedbackCategory")
                        .WithMany("FeedbackScopes")
                        .HasForeignKey("FeedbackCategoryId");

                    b.HasOne("ConferenceApp.Models.Feedback")
                        .WithMany("FeedbackScopes")
                        .HasForeignKey("FeedbackId");
                });

            modelBuilder.Entity("ConferenceApp.Models.Notification", b =>
                {
                    b.HasOne("ConferenceApp.Models.User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ConferenceApp.Models.Role", b =>
                {
                    b.HasOne("ConferenceApp.Models.Event")
                        .WithMany("Roles")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConferenceApp.Models.User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ConferenceApp.Models.Room", b =>
                {
                    b.HasOne("ConferenceApp.Models.EventCentre")
                        .WithMany("Rooms")
                        .HasForeignKey("EventCentreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConferenceApp.Models.Sponsor", b =>
                {
                    b.HasOne("ConferenceApp.Models.Conference")
                        .WithMany("Sponsors")
                        .HasForeignKey("ConferenceId");
                });

            modelBuilder.Entity("ConferenceApp.Models.Sponsorship", b =>
                {
                    b.HasOne("ConferenceApp.Models.ConferenceVersion")
                        .WithMany("Sponsorships")
                        .HasForeignKey("ConferenceVersionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConferenceApp.Models.Sponsor")
                        .WithMany("Sponsorships")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
